Repository futureleadersupc/waw-backend-java, pull requests merged in 2022-06, with the labels that each got.

#1 feat: added shared domain files
  pom.xml
  src/main/java/ga/wawupc/springapi/WawSpringApiApplication.java
  src/main/java/ga/wawupc/springapi/shared/domain/model/AuditModel.java
  src/main/java/ga/wawupc/springapi/shared/domain/service/communication/BaseResponse.java
  src/main/java/ga/wawupc/springapi/shared/exception/ResourceNotFoundException.java
  src/main/java/ga/wawupc/springapi/shared/exception/ResourceValidationException.java
  src/main/java/ga/wawupc/springapi/shared/mapping/EnhancedModelMapper.java
  src/main/java/ga/wawupc/springapi/shared/mapping/MappingConfiguration.java
  src/test/java/ga/wawupc/springapi/WawSpringApiApplicationTests.java
Labels: enhancement

#2 feat: database connection and migrations
  .gitignore
  flyway.example.conf
  pom.xml
  src/main/java/ga/wawupc/springapi/AppConfig.java
  src/main/resources/application.properties
  src/main/resources/database.example.properties
Labels: enhancement

#3 feat(companies): Companies Endpoint
  src/main/java/ga/wawupc/springapi/employers/api/CompaniesController.java
  src/main/java/ga/wawupc/springapi/employers/domain/model/entity/Company.java
  src/main/java/ga/wawupc/springapi/employers/domain/persistence/CompanyRepository.java
  src/main/java/ga/wawupc/springapi/employers/domain/service/CompanyService.java
  src/main/java/ga/wawupc/springapi/employers/mapping/CompanyMapper.java
  src/main/java/ga/wawupc/springapi/employers/mapping/MappingConfiguration.java
  src/main/java/ga/wawupc/springapi/employers/resource/CompanyRequest.java
  src/main/java/ga/wawupc/springapi/employers/resource/CompanyResource.java
  src/main/java/ga/wawupc/springapi/employers/service/CompanyServiceImpl.java
  src/main/java/ga/wawupc/springapi/shared/exception/ResourceValidationException.java
  src/main/resources/db/migration/V20220613210426__.sql
Labels: enhancement

#4 feat(jobs): Job offers endpoint
  src/main/java/ga/wawupc/springapi/jobs/api/OfferController.java
  src/main/java/ga/wawupc/springapi/jobs/domain/model/entity/Offer.java
  src/main/java/ga/wawupc/springapi/jobs/domain/persistence/OfferRepository.java
  src/main/java/ga/wawupc/springapi/jobs/domain/service/OfferService.java
  src/main/java/ga/wawupc/springapi/jobs/mapping/MappingConfiguration.java
  src/main/java/ga/wawupc/springapi/jobs/mapping/OfferMapper.java
  src/main/java/ga/wawupc/springapi/jobs/resource/OfferRequest.java
  src/main/java/ga/wawupc/springapi/jobs/resource/OfferResource.java
  src/main/java/ga/wawupc/springapi/jobs/service/OfferServiceImpl.java
  src/main/java/ga/wawupc/springapi/shared/exception/ResourceValidationException.java
  src/main/resources/db/migration/V20220613223848__CreateOffer.sql
Labels: enhancement

#5 feat(users): Users Endpoint
  src/main/java/ga/wawupc/springapi/auth/api/UsersController.java
  src/main/java/ga/wawupc/springapi/auth/domain/model/entity/User.java
  src/main/java/ga/wawupc/springapi/auth/domain/persistence/UserRepository.java
  src/main/java/ga/wawupc/springapi/auth/domain/service/UserService.java
  src/main/java/ga/wawupc/springapi/auth/mapping/MappingConfiguration.java
  src/main/java/ga/wawupc/springapi/auth/mapping/UserMapper.java
  src/main/java/ga/wawupc/springapi/auth/resource/UserRequest.java
  src/main/java/ga/wawupc/springapi/auth/resource/UserResource.java
  src/main/java/ga/wawupc/springapi/auth/service/UserServiceImpl.java
  src/main/resources/db/migration/V20220614012006__CreateUsers.sql
Labels: enhancement

#6 fix(db): model constraints
  src/main/java/ga/wawupc/springapi/employers/domain/model/entity/Company.java
  src/main/java/ga/wawupc/springapi/jobs/domain/model/entity/Offer.java
  src/main/resources/db/migration/V20220613210426__.sql
  src/main/resources/db/migration/V20220613223848__CreateOffer.sql
  src/main/resources/db/migration/V20220614013123__CreateCompanies.sql
  src/main/resources/db/migration/V20220614014354__CreateOffers.sql
Labels: bug, scope: db

#7 docs: Swagger UI
  .editorconfig
  pom.xml
  src/main/java/ga/wawupc/springapi/WawSpringApiApplication.java
  src/main/java/ga/wawupc/springapi/auth/api/UsersController.java
  src/main/java/ga/wawupc/springapi/employers/api/CompaniesController.java
  src/main/java/ga/wawupc/springapi/employers/service/CompanyServiceImpl.java
  src/main/java/ga/wawupc/springapi/jobs/api/OfferController.java
  src/main/resources/application.properties
Labels: documentation

#8 release: v0.1.0
  .editorconfig
  .gitignore
  flyway.example.conf
  pom.xml
  src/main/java/ga/wawupc/springapi/AppConfig.java
  src/main/java/ga/wawupc/springapi/WawSpringApiApplication.java
  src/main/java/ga/wawupc/springapi/auth/api/UsersController.java
  src/main/java/ga/wawupc/springapi/auth/domain/model/entity/User.java
  src/main/java/ga/wawupc/springapi/auth/domain/persistence/UserRepository.java
  src/main/java/ga/wawupc/springapi/auth/domain/service/UserService.java
  src/main/java/ga/wawupc/springapi/auth/mapping/MappingConfiguration.java
  src/main/java/ga/wawupc/springapi/auth/mapping/UserMapper.java
  src/main/java/ga/wawupc/springapi/auth/resource/UserRequest.java
  src/main/java/ga/wawupc/springapi/auth/resource/UserResource.java
  src/main/java/ga/wawupc/springapi/auth/service/UserServiceImpl.java
  src/main/java/ga/wawupc/springapi/employers/api/CompaniesController.java
  src/main/java/ga/wawupc/springapi/employers/domain/model/entity/Company.java
  src/main/java/ga/wawupc/springapi/employers/domain/persistence/CompanyRepository.java
  src/main/java/ga/wawupc/springapi/employers/domain/service/CompanyService.java
  src/main/java/ga/wawupc/springapi/employers/mapping/CompanyMapper.java
  src/main/java/ga/wawupc/springapi/employers/mapping/MappingConfiguration.java
  src/main/java/ga/wawupc/springapi/employers/resource/CompanyRequest.java
  src/main/java/ga/wawupc/springapi/employers/resource/CompanyResource.java
  src/main/java/ga/wawupc/springapi/employers/service/CompanyServiceImpl.java
  src/main/java/ga/wawupc/springapi/jobs/api/OfferController.java
  src/main/java/ga/wawupc/springapi/jobs/domain/model/entity/Offer.java
  src/main/java/ga/wawupc/springapi/jobs/domain/persistence/OfferRepository.java
  src/main/java/ga/wawupc/springapi/jobs/domain/service/OfferService.java
  src/main/java/ga/wawupc/springapi/jobs/mapping/MappingConfiguration.java
  src/main/java/ga/wawupc/springapi/jobs/mapping/OfferMapper.java
  src/main/java/ga/wawupc/springapi/jobs/resource/OfferRequest.java
  src/main/java/ga/wawupc/springapi/jobs/resource/OfferResource.java
  src/main/java/ga/wawupc/springapi/jobs/service/OfferServiceImpl.java
  src/main/java/ga/wawupc/springapi/shared/domain/model/AuditModel.java
  src/main/java/ga/wawupc/springapi/shared/domain/service/communication/BaseResponse.java
  src/main/java/ga/wawupc/springapi/shared/exception/ResourceNotFoundException.java
  src/main/java/ga/wawupc/springapi/shared/exception/ResourceValidationException.java
  src/main/java/ga/wawupc/springapi/shared/mapping/EnhancedModelMapper.java
  src/main/java/ga/wawupc/springapi/shared/mapping/MappingConfiguration.java
  src/main/resources/application.properties
  src/main/resources/database.example.properties
  src/main/resources/db/migration/V20220614012006__CreateUsers.sql
  src/main/resources/db/migration/V20220614013123__CreateCompanies.sql
  src/main/resources/db/migration/V20220614014354__CreateOffers.sql
  src/test/java/ga/wawupc/springapi/WawSpringApiApplicationTests.java
Labels: enhancement

#9 chore(ci): deployment
  .gcloudignore
  .github/workflows/deploy.yml
  .github/workflows/maven.yml
  .gitignore
  pom.xml
  src/main/appengine/app.yaml
  src/main/java/ga/wawupc/springapi/shared/domain/service/communication/BaseResponse.java
  src/main/resources/application-cloudsql.properties
  src/main/resources/application-mysql.example.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/database.example.properties
Labels: chore, ci
